name: internapp
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.13
  floating_bottom_nav_bar_list:
    git: "https://github.com/alnaughty/floating_bottom_nav_list"
  page_transition: ^2.0.5
  http:
  rxdart: ^0.27.3
  intl: ^0.17.0
  jiffy: ^5.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_verification_code: ^1.1.2+1
  flutter_slidable: ^1.2.0
  loading_animation_widget: ^1.2.0+3
  fluttertoast: ^8.0.9
  # qr_code_scanner: ^0.7.0
  # flutter_barcode_scanner: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appIcon.png"


flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/

